# Planet configuration file

# Every planet needs a [Planet] section
[Planet]
# name: Your planet's name
# link: Link to the main page
# owner_name: Your name
# owner_email: Your e-mail address
name = Techmeme Leaderboard
link = http://planet.intertwingly.net/top100/
owner_name = Sam Ruby
owner_email = rubys@intertwingly.net

# cache_directory: Where cached feeds are stored
# log_level: One of DEBUG, INFO, WARNING, ERROR or CRITICAL
# render_html = false | default does not render html in summaries
cache_directory = /home/rubys/planet/top100
log_level = INFO

# Output files:
# output_dir: Directory to place output files
# items_per_page: How many items to put on each page
output_dir = /home/rubys/public_html/top100
items_per_page = 60

# If non-zero, all feeds which have not been updated in the indicated
# number of days will be marked as inactive
# activity_threshold = 90

# add built-in excerpts to cached entries
# excerpt = true

# Don't let any one feed monopolize the output (symptom often occurs when
# somebody 'migrates' their weblog.
new_feed_items = 4

# subscriptions
[https://example.com/feed.xml]
name = Example Feed
